keycloak:
  realm: kwetter
  auth-server-url: http://localhost:8082/auth
  ssl-required: external
  resource: kwetter-backend-app
  credentials:
    secret: wqIwja45PSkAWaU01z6SGWT2B8q97kKUcpX2ujZS0DgO4KQyyGecZJvxyRbsEyIm
  use-resource-role-mappings: true
spring:
  datasource:
    url: jdbc:postgresql://localhost/kwetter
    username: kwetter
    password: E24Hhla1xEy4UGXcJ0mGb9dMhVLxrrrl
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      temp.use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
